version: '3.7'

services:
    postgres:
        image: postgres:11.7-alpine
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DB}
        restart: always

    server:
        build: .
        restart: always
        ports:
            - "5000:5000"
        links:
            - "postgres:db"
        depends_on:
            - postgres